#Teacher-Training.md 번역
ClojureBridgeSeoul/organizing pull request #7
Opened 2017-02-27 12:01 UTC by snowTUBE

- hint, hint! 부분을 봐주셨으면 합니다.

2017-02-27 12:16 UTC, dalzony requested changes
나머지는 좋습니다. 약간 걸리는 것은 `수업 연수`외에 좋은 단어를 고르고 싶은데 아직 잘 생각이 안나네요 ㅋ

2017-02-27 12:16 UTC, dalzony commented on Teacher-Training.md
> +_저희는 참가자들이 ClojureBridge에 이것을 구체적으로 적용시켰으면 합니다. - 화이팅, 화이팅!_
`RailsBridge teacher training`를 힌트 삼아서, 클로저 브릿지에 잘 적용했으면 좋겠다라는 것 같은데.
이렇게 하면 어떨까요?

```
좋은 선생님이 되기위해 `레일즈브릿지`의 프리젠테이션을 참고하고 이를 클로저 브릿지에 적용하기를 바랍니다.
```

2017-02-27 12:49 UTC, snowTUBE commented
수정했습니다.

2017-02-28 13:31 UTC, merged

2017-02-28 13:31 UTC, dalzony commented
@snowTUBE 감사합니다 👍